CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE gyms (
    "GymId" uuid NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Address" text NOT NULL,
    "IsApproved" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_gyms" PRIMARY KEY ("GymId")
);

CREATE TABLE locations (
    "LocationID" uuid NOT NULL,
    "Latitude" numeric(18,6) NOT NULL,
    "Longitude" numeric(18,6) NOT NULL,
    "City" text NOT NULL,
    "Country" text NOT NULL,
    CONSTRAINT "PK_locations" PRIMARY KEY ("LocationID")
);

CREATE TABLE roles (
    roleid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY (roleid)
);

CREATE TABLE users (
    userid uuid NOT NULL,
    fullname text NOT NULL,
    email text NOT NULL,
    phone text,
    passwordhash text NOT NULL,
    location text,
    dateofbirth timestamp without time zone,
    membershipid uuid,
    gender text,
    createdat timestamp without time zone NOT NULL,
    isactive boolean NOT NULL DEFAULT TRUE,
    biography character varying(500),
    profilepictureurl text,
    haschangedname boolean NOT NULL DEFAULT FALSE,
    medicalconditions text,
    emergencycontact text,
    refreshtoken text,
    refreshtokenexpiry timestamp without time zone,
    CONSTRAINT "PK_users" PRIMARY KEY (userid)
);

CREATE TABLE gymbranches (
    "GymBranchID" uuid NOT NULL,
    "GymID" uuid NOT NULL,
    "LocationID" uuid NOT NULL,
    "Name" text NOT NULL,
    "OperatingHours" jsonb NOT NULL,
    "ServiceDescription" text,
    "CoverImageUrl" text,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_gymbranches" PRIMARY KEY ("GymBranchID"),
    CONSTRAINT "FK_gymbranches_gyms_GymID" FOREIGN KEY ("GymID") REFERENCES gyms ("GymId") ON DELETE CASCADE,
    CONSTRAINT "FK_gymbranches_locations_LocationID" FOREIGN KEY ("LocationID") REFERENCES locations ("LocationID") ON DELETE CASCADE
);

CREATE TABLE memberships (
    "MembershipID" uuid NOT NULL,
    "UserID" uuid NOT NULL,
    "GymID" uuid NOT NULL,
    "IsMember" boolean NOT NULL,
    "ExpiryDate" timestamp without time zone,
    "JoinedAt" timestamp without time zone NOT NULL,
    "RemovedAt" timestamp without time zone,
    "Description" text,
    CONSTRAINT "PK_memberships" PRIMARY KEY ("MembershipID"),
    CONSTRAINT "FK_memberships_gyms_GymID" FOREIGN KEY ("GymID") REFERENCES gyms ("GymId") ON DELETE CASCADE,
    CONSTRAINT "FK_memberships_users_UserID" FOREIGN KEY ("UserID") REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE systemadminactions (
    systemadminactionid uuid NOT NULL,
    "UserID" uuid NOT NULL,
    "ActionType" character varying(100) NOT NULL,
    "TargetEntity" character varying(100) NOT NULL,
    "TargetID" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "Outcome" text NOT NULL,
    CONSTRAINT "PK_systemadminactions" PRIMARY KEY (systemadminactionid),
    CONSTRAINT "FK_systemadminactions_users_UserID" FOREIGN KEY ("UserID") REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE userrole (
    userroleid integer GENERATED BY DEFAULT AS IDENTITY,
    userid uuid NOT NULL,
    roleid integer NOT NULL,
    CONSTRAINT "PK_userrole" PRIMARY KEY (userroleid),
    CONSTRAINT "FK_userrole_roles_roleid" FOREIGN KEY (roleid) REFERENCES roles (roleid) ON DELETE CASCADE,
    CONSTRAINT "FK_userrole_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE announcements (
    announcementid uuid NOT NULL,
    "GymBranchID" uuid NOT NULL,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ExpiresAt" timestamp without time zone,
    CONSTRAINT "PK_announcements" PRIMARY KEY (announcementid),
    CONSTRAINT "FK_announcements_gymbranches_GymBranchID" FOREIGN KEY ("GymBranchID") REFERENCES gymbranches ("GymBranchID") ON DELETE CASCADE
);

CREATE TABLE gymadminactions (
    gymadminactionid uuid NOT NULL,
    "UserID" uuid NOT NULL,
    "GymBranchID" uuid NOT NULL,
    "ActionType" character varying(100) NOT NULL,
    "TargetEntity" character varying(100) NOT NULL,
    "TargetID" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "Outcome" character varying(255) NOT NULL,
    CONSTRAINT "PK_gymadminactions" PRIMARY KEY (gymadminactionid),
    CONSTRAINT "FK_gymadminactions_gymbranches_GymBranchID" FOREIGN KEY ("GymBranchID") REFERENCES gymbranches ("GymBranchID") ON DELETE CASCADE,
    CONSTRAINT "FK_gymadminactions_users_UserID" FOREIGN KEY ("UserID") REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE gymsessions (
    "GymSessionID" uuid NOT NULL,
    "UserID" uuid NOT NULL,
    "GymBranchID" uuid NOT NULL,
    "CheckInTime" timestamp without time zone NOT NULL,
    "CheckOutTime" timestamp without time zone,
    "SessionDuration" integer,
    "CheckInLat" numeric(18,6) NOT NULL,
    "CheckInLong" numeric(18,6) NOT NULL,
    "IsVerifiedLocation" boolean NOT NULL,
    CONSTRAINT "PK_gymsessions" PRIMARY KEY ("GymSessionID"),
    CONSTRAINT "FK_gymsessions_gymbranches_GymBranchID" FOREIGN KEY ("GymBranchID") REFERENCES gymbranches ("GymBranchID") ON DELETE CASCADE,
    CONSTRAINT "FK_gymsessions_users_UserID" FOREIGN KEY ("UserID") REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE notifications (
    notificationid uuid NOT NULL,
    "UserID" uuid,
    "GymBranchID" uuid,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "SentAt" timestamp without time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_notifications" PRIMARY KEY (notificationid),
    CONSTRAINT "FK_notifications_gymbranches_GymBranchID" FOREIGN KEY ("GymBranchID") REFERENCES gymbranches ("GymBranchID"),
    CONSTRAINT "FK_notifications_users_UserID" FOREIGN KEY ("UserID") REFERENCES users (userid)
);

CREATE TABLE traffictrack (
    "TrafficTrackID" uuid NOT NULL,
    "GymBranchID" uuid NOT NULL,
    "TrafficTimestamp" timestamp without time zone NOT NULL,
    "CapacityPercentage" numeric(5,2),
    "EntryCount" integer NOT NULL,
    "IsRead" boolean,
    CONSTRAINT "PK_traffictrack" PRIMARY KEY ("TrafficTrackID"),
    CONSTRAINT "FK_traffictrack_gymbranches_GymBranchID" FOREIGN KEY ("GymBranchID") REFERENCES gymbranches ("GymBranchID") ON DELETE CASCADE
);

CREATE TABLE usernotification (
    usernotificationid integer GENERATED BY DEFAULT AS IDENTITY,
    userid uuid NOT NULL,
    notificationid uuid NOT NULL,
    readstatus boolean NOT NULL DEFAULT FALSE,
    readat timestamp without time zone,
    CONSTRAINT "PK_usernotification" PRIMARY KEY (usernotificationid),
    CONSTRAINT "FK_usernotification_notifications_notificationid" FOREIGN KEY (notificationid) REFERENCES notifications (notificationid) ON DELETE CASCADE,
    CONSTRAINT "FK_usernotification_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE INDEX "IX_announcements_GymBranchID" ON announcements ("GymBranchID");

CREATE INDEX "IX_gymadminactions_GymBranchID" ON gymadminactions ("GymBranchID");

CREATE INDEX "IX_gymadminactions_UserID" ON gymadminactions ("UserID");

CREATE INDEX "IX_gymbranches_GymID" ON gymbranches ("GymID");

CREATE INDEX "IX_gymbranches_LocationID" ON gymbranches ("LocationID");

CREATE INDEX "IX_gymsessions_GymBranchID" ON gymsessions ("GymBranchID");

CREATE INDEX "IX_gymsessions_UserID" ON gymsessions ("UserID");

CREATE INDEX "IX_memberships_GymID" ON memberships ("GymID");

CREATE INDEX "IX_memberships_UserID" ON memberships ("UserID");

CREATE INDEX "IX_notifications_GymBranchID" ON notifications ("GymBranchID");

CREATE INDEX "IX_notifications_UserID" ON notifications ("UserID");

CREATE INDEX "IX_systemadminactions_UserID" ON systemadminactions ("UserID");

CREATE INDEX "IX_traffictrack_GymBranchID" ON traffictrack ("GymBranchID");

CREATE INDEX "IX_usernotification_notificationid" ON usernotification (notificationid);

CREATE UNIQUE INDEX "IX_usernotification_userid_notificationid" ON usernotification (userid, notificationid);

CREATE INDEX "IX_userrole_roleid" ON userrole (roleid);

CREATE UNIQUE INDEX "IX_userrole_userid_roleid" ON userrole (userid, roleid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209211300_AddTwoNewColumnsToUser', '10.0.2');

COMMIT;

