// <auto-generated />
using System;
using System.Text.Json;
using GYMIND.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GYMIND.API.Migrations
{
    [DbContext(typeof(SupabaseDbContext))]
    partial class SupabaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GYMIND.API.Entities.Announcement", b =>
                {
                    b.Property<Guid>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("announcementid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GymBranchID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnouncementID");

                    b.HasIndex("GymBranchID");

                    b.ToTable("announcement", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.Gym", b =>
                {
                    b.Property<Guid>("GymID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("gymid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isapproved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("GymID");

                    b.ToTable("gym", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymAdminAction", b =>
                {
                    b.Property<Guid>("GymAdminActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("gymadminactionid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GymBranchID")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TargetID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("GymAdminActionID");

                    b.HasIndex("GymBranchID");

                    b.HasIndex("UserID");

                    b.ToTable("gymadminaction", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymBranch", b =>
                {
                    b.Property<Guid>("GymBranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coverimageurl");

                    b.Property<Guid>("GymID")
                        .HasColumnType("uuid")
                        .HasColumnName("gymid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uuid")
                        .HasColumnName("locationid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("OperatingHours")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("servicedescription");

                    b.HasKey("GymBranchID");

                    b.HasIndex("GymID");

                    b.HasIndex("LocationID");

                    b.ToTable("gymbranch", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymSession", b =>
                {
                    b.Property<Guid>("GymSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CheckInLat")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("CheckInLong")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CheckOutTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GymBranchID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerifiedLocation")
                        .HasColumnType("boolean");

                    b.Property<int?>("SessionDuration")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("GymSessionID");

                    b.HasIndex("GymBranchID");

                    b.HasIndex("UserID");

                    b.ToTable("gymsession", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("LocationID");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.Membership", b =>
                {
                    b.Property<Guid>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("membershipid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GymBranchID")
                        .HasColumnType("uuid")
                        .HasColumnName("gymbranchid");

                    b.Property<Guid>("GymID")
                        .HasColumnType("uuid")
                        .HasColumnName("gymid");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean")
                        .HasColumnName("ismember");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joinedat");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("removedat");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("MembershipID");

                    b.HasIndex("GymBranchID");

                    b.HasIndex("GymID");

                    b.HasIndex("UserID");

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notificationid");

                    b.Property<Guid?>("GymBranchID")
                        .HasColumnType("uuid")
                        .HasColumnName("gymbranchid");

                    b.Property<Guid?>("GymID")
                        .HasColumnType("uuid")
                        .HasColumnName("gymid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sentat");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("NotificationID");

                    b.HasIndex("GymBranchID");

                    b.HasIndex("GymID");

                    b.HasIndex("UserID");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleID");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.SystemAdminAction", b =>
                {
                    b.Property<Guid>("SystemAdminActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("systemadminactionid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TargetID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("SystemAdminActionID");

                    b.HasIndex("UserID");

                    b.ToTable("systemadminactions", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.TrafficTrack", b =>
                {
                    b.Property<Guid>("TrafficTrackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CapacityPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GymBranchID")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TrafficTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TrafficTrackID");

                    b.HasIndex("GymBranchID");

                    b.ToTable("traffictrack", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("text")
                        .HasColumnName("emergencycontact");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("HasChangedName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("haschangedname");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("text")
                        .HasColumnName("medicalconditions");

                    b.Property<Guid?>("MembershipID")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profilepictureurl");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refreshtokenexpiry");

                    b.HasKey("UserID");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("UserNotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usernotificationid");

                    b.Property<Guid>("NotificationID")
                        .HasColumnType("uuid")
                        .HasColumnName("notificationid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("readat");

                    b.Property<bool>("ReadStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("readstatus");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("UserNotificationID");

                    b.HasIndex("NotificationID");

                    b.HasIndex("UserID", "NotificationID")
                        .IsUnique();

                    b.ToTable("usernotification", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userroleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID", "RoleID")
                        .IsUnique();

                    b.ToTable("userrole", (string)null);
                });

            modelBuilder.Entity("GYMIND.API.Entities.Announcement", b =>
                {
                    b.HasOne("GYMIND.API.Entities.GymBranch", "GymBranch")
                        .WithMany()
                        .HasForeignKey("GymBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymBranch");
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymAdminAction", b =>
                {
                    b.HasOne("GYMIND.API.Entities.GymBranch", "GymBranch")
                        .WithMany()
                        .HasForeignKey("GymBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymBranch", b =>
                {
                    b.HasOne("GYMIND.API.Entities.Gym", "Gym")
                        .WithMany("GymBranches")
                        .HasForeignKey("GymID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYMIND.API.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymSession", b =>
                {
                    b.HasOne("GYMIND.API.Entities.GymBranch", "GymBranch")
                        .WithMany()
                        .HasForeignKey("GymBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.Membership", b =>
                {
                    b.HasOne("GYMIND.API.Entities.GymBranch", "GymBranch")
                        .WithMany("Memberships")
                        .HasForeignKey("GymBranchID");

                    b.HasOne("GYMIND.API.Entities.Gym", "Gym")
                        .WithMany("Memberships")
                        .HasForeignKey("GymID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.Notification", b =>
                {
                    b.HasOne("GYMIND.API.Entities.GymBranch", "GymBranch")
                        .WithMany()
                        .HasForeignKey("GymBranchID");

                    b.HasOne("GYMIND.API.Entities.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymID");

                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Gym");

                    b.Navigation("GymBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.SystemAdminAction", b =>
                {
                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.TrafficTrack", b =>
                {
                    b.HasOne("GYMIND.API.Entities.GymBranch", "GymBranch")
                        .WithMany()
                        .HasForeignKey("GymBranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymBranch");
                });

            modelBuilder.Entity("GYMIND.API.Entities.UserNotification", b =>
                {
                    b.HasOne("GYMIND.API.Entities.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.UserRole", b =>
                {
                    b.HasOne("GYMIND.API.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYMIND.API.Entities.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYMIND.API.Entities.Gym", b =>
                {
                    b.Navigation("GymBranches");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("GYMIND.API.Entities.GymBranch", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("GYMIND.API.Entities.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("GYMIND.API.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GYMIND.API.Entities.User", b =>
                {
                    b.Navigation("UserNotifications");

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
